// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/eclipse-cfm/cfm/pmanager/api"

	mock "github.com/stretchr/testify/mock"

	query "github.com/eclipse-cfm/cfm/common/query"
)

// MockDefinitionManager is an autogenerated mock type for the DefinitionManager type
type MockDefinitionManager struct {
	mock.Mock
}

type MockDefinitionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDefinitionManager) EXPECT() *MockDefinitionManager_Expecter {
	return &MockDefinitionManager_Expecter{mock: &_m.Mock}
}

// CreateActivityDefinition provides a mock function with given fields: ctx, definition
func (_m *MockDefinitionManager) CreateActivityDefinition(ctx context.Context, definition *api.ActivityDefinition) (*api.ActivityDefinition, error) {
	ret := _m.Called(ctx, definition)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivityDefinition")
	}

	var r0 *api.ActivityDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ActivityDefinition) (*api.ActivityDefinition, error)); ok {
		return rf(ctx, definition)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.ActivityDefinition) *api.ActivityDefinition); ok {
		r0 = rf(ctx, definition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ActivityDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.ActivityDefinition) error); ok {
		r1 = rf(ctx, definition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefinitionManager_CreateActivityDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivityDefinition'
type MockDefinitionManager_CreateActivityDefinition_Call struct {
	*mock.Call
}

// CreateActivityDefinition is a helper method to define mock.On call
//   - ctx context.Context
//   - definition *api.ActivityDefinition
func (_e *MockDefinitionManager_Expecter) CreateActivityDefinition(ctx interface{}, definition interface{}) *MockDefinitionManager_CreateActivityDefinition_Call {
	return &MockDefinitionManager_CreateActivityDefinition_Call{Call: _e.mock.On("CreateActivityDefinition", ctx, definition)}
}

func (_c *MockDefinitionManager_CreateActivityDefinition_Call) Run(run func(ctx context.Context, definition *api.ActivityDefinition)) *MockDefinitionManager_CreateActivityDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.ActivityDefinition))
	})
	return _c
}

func (_c *MockDefinitionManager_CreateActivityDefinition_Call) Return(_a0 *api.ActivityDefinition, _a1 error) *MockDefinitionManager_CreateActivityDefinition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefinitionManager_CreateActivityDefinition_Call) RunAndReturn(run func(context.Context, *api.ActivityDefinition) (*api.ActivityDefinition, error)) *MockDefinitionManager_CreateActivityDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrchestrationDefinition provides a mock function with given fields: ctx, definition
func (_m *MockDefinitionManager) CreateOrchestrationDefinition(ctx context.Context, definition *api.OrchestrationDefinition) (*api.OrchestrationDefinition, error) {
	ret := _m.Called(ctx, definition)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrchestrationDefinition")
	}

	var r0 *api.OrchestrationDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.OrchestrationDefinition) (*api.OrchestrationDefinition, error)); ok {
		return rf(ctx, definition)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.OrchestrationDefinition) *api.OrchestrationDefinition); ok {
		r0 = rf(ctx, definition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.OrchestrationDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.OrchestrationDefinition) error); ok {
		r1 = rf(ctx, definition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefinitionManager_CreateOrchestrationDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrchestrationDefinition'
type MockDefinitionManager_CreateOrchestrationDefinition_Call struct {
	*mock.Call
}

// CreateOrchestrationDefinition is a helper method to define mock.On call
//   - ctx context.Context
//   - definition *api.OrchestrationDefinition
func (_e *MockDefinitionManager_Expecter) CreateOrchestrationDefinition(ctx interface{}, definition interface{}) *MockDefinitionManager_CreateOrchestrationDefinition_Call {
	return &MockDefinitionManager_CreateOrchestrationDefinition_Call{Call: _e.mock.On("CreateOrchestrationDefinition", ctx, definition)}
}

func (_c *MockDefinitionManager_CreateOrchestrationDefinition_Call) Run(run func(ctx context.Context, definition *api.OrchestrationDefinition)) *MockDefinitionManager_CreateOrchestrationDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.OrchestrationDefinition))
	})
	return _c
}

func (_c *MockDefinitionManager_CreateOrchestrationDefinition_Call) Return(_a0 *api.OrchestrationDefinition, _a1 error) *MockDefinitionManager_CreateOrchestrationDefinition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefinitionManager_CreateOrchestrationDefinition_Call) RunAndReturn(run func(context.Context, *api.OrchestrationDefinition) (*api.OrchestrationDefinition, error)) *MockDefinitionManager_CreateOrchestrationDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActivityDefinition provides a mock function with given fields: ctx, atype
func (_m *MockDefinitionManager) DeleteActivityDefinition(ctx context.Context, atype api.ActivityType) error {
	ret := _m.Called(ctx, atype)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActivityDefinition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.ActivityType) error); ok {
		r0 = rf(ctx, atype)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDefinitionManager_DeleteActivityDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActivityDefinition'
type MockDefinitionManager_DeleteActivityDefinition_Call struct {
	*mock.Call
}

// DeleteActivityDefinition is a helper method to define mock.On call
//   - ctx context.Context
//   - atype api.ActivityType
func (_e *MockDefinitionManager_Expecter) DeleteActivityDefinition(ctx interface{}, atype interface{}) *MockDefinitionManager_DeleteActivityDefinition_Call {
	return &MockDefinitionManager_DeleteActivityDefinition_Call{Call: _e.mock.On("DeleteActivityDefinition", ctx, atype)}
}

func (_c *MockDefinitionManager_DeleteActivityDefinition_Call) Run(run func(ctx context.Context, atype api.ActivityType)) *MockDefinitionManager_DeleteActivityDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.ActivityType))
	})
	return _c
}

func (_c *MockDefinitionManager_DeleteActivityDefinition_Call) Return(_a0 error) *MockDefinitionManager_DeleteActivityDefinition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDefinitionManager_DeleteActivityDefinition_Call) RunAndReturn(run func(context.Context, api.ActivityType) error) *MockDefinitionManager_DeleteActivityDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrchestrationDefinition provides a mock function with given fields: ctx, templateRef
func (_m *MockDefinitionManager) DeleteOrchestrationDefinition(ctx context.Context, templateRef string) error {
	ret := _m.Called(ctx, templateRef)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrchestrationDefinition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, templateRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDefinitionManager_DeleteOrchestrationDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrchestrationDefinition'
type MockDefinitionManager_DeleteOrchestrationDefinition_Call struct {
	*mock.Call
}

// DeleteOrchestrationDefinition is a helper method to define mock.On call
//   - ctx context.Context
//   - templateRef string
func (_e *MockDefinitionManager_Expecter) DeleteOrchestrationDefinition(ctx interface{}, templateRef interface{}) *MockDefinitionManager_DeleteOrchestrationDefinition_Call {
	return &MockDefinitionManager_DeleteOrchestrationDefinition_Call{Call: _e.mock.On("DeleteOrchestrationDefinition", ctx, templateRef)}
}

func (_c *MockDefinitionManager_DeleteOrchestrationDefinition_Call) Run(run func(ctx context.Context, templateRef string)) *MockDefinitionManager_DeleteOrchestrationDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDefinitionManager_DeleteOrchestrationDefinition_Call) Return(_a0 error) *MockDefinitionManager_DeleteOrchestrationDefinition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDefinitionManager_DeleteOrchestrationDefinition_Call) RunAndReturn(run func(context.Context, string) error) *MockDefinitionManager_DeleteOrchestrationDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityDefinitions provides a mock function with given fields: ctx
func (_m *MockDefinitionManager) GetActivityDefinitions(ctx context.Context) ([]api.ActivityDefinition, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityDefinitions")
	}

	var r0 []api.ActivityDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]api.ActivityDefinition, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []api.ActivityDefinition); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.ActivityDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefinitionManager_GetActivityDefinitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityDefinitions'
type MockDefinitionManager_GetActivityDefinitions_Call struct {
	*mock.Call
}

// GetActivityDefinitions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDefinitionManager_Expecter) GetActivityDefinitions(ctx interface{}) *MockDefinitionManager_GetActivityDefinitions_Call {
	return &MockDefinitionManager_GetActivityDefinitions_Call{Call: _e.mock.On("GetActivityDefinitions", ctx)}
}

func (_c *MockDefinitionManager_GetActivityDefinitions_Call) Run(run func(ctx context.Context)) *MockDefinitionManager_GetActivityDefinitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDefinitionManager_GetActivityDefinitions_Call) Return(_a0 []api.ActivityDefinition, _a1 error) *MockDefinitionManager_GetActivityDefinitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefinitionManager_GetActivityDefinitions_Call) RunAndReturn(run func(context.Context) ([]api.ActivityDefinition, error)) *MockDefinitionManager_GetActivityDefinitions_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrchestrationDefinitions provides a mock function with given fields: ctx
func (_m *MockDefinitionManager) GetOrchestrationDefinitions(ctx context.Context) ([]api.OrchestrationDefinition, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrchestrationDefinitions")
	}

	var r0 []api.OrchestrationDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]api.OrchestrationDefinition, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []api.OrchestrationDefinition); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.OrchestrationDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefinitionManager_GetOrchestrationDefinitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrchestrationDefinitions'
type MockDefinitionManager_GetOrchestrationDefinitions_Call struct {
	*mock.Call
}

// GetOrchestrationDefinitions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDefinitionManager_Expecter) GetOrchestrationDefinitions(ctx interface{}) *MockDefinitionManager_GetOrchestrationDefinitions_Call {
	return &MockDefinitionManager_GetOrchestrationDefinitions_Call{Call: _e.mock.On("GetOrchestrationDefinitions", ctx)}
}

func (_c *MockDefinitionManager_GetOrchestrationDefinitions_Call) Run(run func(ctx context.Context)) *MockDefinitionManager_GetOrchestrationDefinitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDefinitionManager_GetOrchestrationDefinitions_Call) Return(_a0 []api.OrchestrationDefinition, _a1 error) *MockDefinitionManager_GetOrchestrationDefinitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefinitionManager_GetOrchestrationDefinitions_Call) RunAndReturn(run func(context.Context) ([]api.OrchestrationDefinition, error)) *MockDefinitionManager_GetOrchestrationDefinitions_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrchestrationDefinitionsByTemplate provides a mock function with given fields: ctx, templateRef
func (_m *MockDefinitionManager) GetOrchestrationDefinitionsByTemplate(ctx context.Context, templateRef string) ([]api.OrchestrationDefinition, error) {
	ret := _m.Called(ctx, templateRef)

	if len(ret) == 0 {
		panic("no return value specified for GetOrchestrationDefinitionsByTemplate")
	}

	var r0 []api.OrchestrationDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]api.OrchestrationDefinition, error)); ok {
		return rf(ctx, templateRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []api.OrchestrationDefinition); ok {
		r0 = rf(ctx, templateRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.OrchestrationDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, templateRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrchestrationDefinitionsByTemplate'
type MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call struct {
	*mock.Call
}

// GetOrchestrationDefinitionsByTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - templateRef string
func (_e *MockDefinitionManager_Expecter) GetOrchestrationDefinitionsByTemplate(ctx interface{}, templateRef interface{}) *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call {
	return &MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call{Call: _e.mock.On("GetOrchestrationDefinitionsByTemplate", ctx, templateRef)}
}

func (_c *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call) Run(run func(ctx context.Context, templateRef string)) *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call) Return(_a0 []api.OrchestrationDefinition, _a1 error) *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call) RunAndReturn(run func(context.Context, string) ([]api.OrchestrationDefinition, error)) *MockDefinitionManager_GetOrchestrationDefinitionsByTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// QueryOrchestrationDefinitions provides a mock function with given fields: ctx, predicate
func (_m *MockDefinitionManager) QueryOrchestrationDefinitions(ctx context.Context, predicate query.Predicate) ([]api.OrchestrationDefinition, error) {
	ret := _m.Called(ctx, predicate)

	if len(ret) == 0 {
		panic("no return value specified for QueryOrchestrationDefinitions")
	}

	var r0 []api.OrchestrationDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) ([]api.OrchestrationDefinition, error)); ok {
		return rf(ctx, predicate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) []api.OrchestrationDefinition); ok {
		r0 = rf(ctx, predicate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.OrchestrationDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Predicate) error); ok {
		r1 = rf(ctx, predicate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefinitionManager_QueryOrchestrationDefinitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryOrchestrationDefinitions'
type MockDefinitionManager_QueryOrchestrationDefinitions_Call struct {
	*mock.Call
}

// QueryOrchestrationDefinitions is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
func (_e *MockDefinitionManager_Expecter) QueryOrchestrationDefinitions(ctx interface{}, predicate interface{}) *MockDefinitionManager_QueryOrchestrationDefinitions_Call {
	return &MockDefinitionManager_QueryOrchestrationDefinitions_Call{Call: _e.mock.On("QueryOrchestrationDefinitions", ctx, predicate)}
}

func (_c *MockDefinitionManager_QueryOrchestrationDefinitions_Call) Run(run func(ctx context.Context, predicate query.Predicate)) *MockDefinitionManager_QueryOrchestrationDefinitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate))
	})
	return _c
}

func (_c *MockDefinitionManager_QueryOrchestrationDefinitions_Call) Return(_a0 []api.OrchestrationDefinition, _a1 error) *MockDefinitionManager_QueryOrchestrationDefinitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefinitionManager_QueryOrchestrationDefinitions_Call) RunAndReturn(run func(context.Context, query.Predicate) ([]api.OrchestrationDefinition, error)) *MockDefinitionManager_QueryOrchestrationDefinitions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDefinitionManager creates a new instance of MockDefinitionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDefinitionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDefinitionManager {
	mock := &MockDefinitionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
