// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/eclipse-cfm/cfm/pmanager/api"

	iter "iter"

	mock "github.com/stretchr/testify/mock"

	model "github.com/eclipse-cfm/cfm/common/model"

	query "github.com/eclipse-cfm/cfm/common/query"

	store "github.com/eclipse-cfm/cfm/common/store"
)

// MockProvisionManager is an autogenerated mock type for the ProvisionManager type
type MockProvisionManager struct {
	mock.Mock
}

type MockProvisionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvisionManager) EXPECT() *MockProvisionManager_Expecter {
	return &MockProvisionManager_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, orchestrationID
func (_m *MockProvisionManager) Cancel(ctx context.Context, orchestrationID string) error {
	ret := _m.Called(ctx, orchestrationID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orchestrationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvisionManager_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockProvisionManager_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orchestrationID string
func (_e *MockProvisionManager_Expecter) Cancel(ctx interface{}, orchestrationID interface{}) *MockProvisionManager_Cancel_Call {
	return &MockProvisionManager_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orchestrationID)}
}

func (_c *MockProvisionManager_Cancel_Call) Run(run func(ctx context.Context, orchestrationID string)) *MockProvisionManager_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProvisionManager_Cancel_Call) Return(_a0 error) *MockProvisionManager_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvisionManager_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *MockProvisionManager_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// CountOrchestrations provides a mock function with given fields: ctx, predicate
func (_m *MockProvisionManager) CountOrchestrations(ctx context.Context, predicate query.Predicate) (int64, error) {
	ret := _m.Called(ctx, predicate)

	if len(ret) == 0 {
		panic("no return value specified for CountOrchestrations")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) (int64, error)); ok {
		return rf(ctx, predicate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) int64); ok {
		r0 = rf(ctx, predicate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Predicate) error); ok {
		r1 = rf(ctx, predicate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvisionManager_CountOrchestrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOrchestrations'
type MockProvisionManager_CountOrchestrations_Call struct {
	*mock.Call
}

// CountOrchestrations is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
func (_e *MockProvisionManager_Expecter) CountOrchestrations(ctx interface{}, predicate interface{}) *MockProvisionManager_CountOrchestrations_Call {
	return &MockProvisionManager_CountOrchestrations_Call{Call: _e.mock.On("CountOrchestrations", ctx, predicate)}
}

func (_c *MockProvisionManager_CountOrchestrations_Call) Run(run func(ctx context.Context, predicate query.Predicate)) *MockProvisionManager_CountOrchestrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate))
	})
	return _c
}

func (_c *MockProvisionManager_CountOrchestrations_Call) Return(_a0 int64, _a1 error) *MockProvisionManager_CountOrchestrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvisionManager_CountOrchestrations_Call) RunAndReturn(run func(context.Context, query.Predicate) (int64, error)) *MockProvisionManager_CountOrchestrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrchestration provides a mock function with given fields: ctx, orchestrationID
func (_m *MockProvisionManager) GetOrchestration(ctx context.Context, orchestrationID string) (*api.Orchestration, error) {
	ret := _m.Called(ctx, orchestrationID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrchestration")
	}

	var r0 *api.Orchestration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.Orchestration, error)); ok {
		return rf(ctx, orchestrationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.Orchestration); ok {
		r0 = rf(ctx, orchestrationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Orchestration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orchestrationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvisionManager_GetOrchestration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrchestration'
type MockProvisionManager_GetOrchestration_Call struct {
	*mock.Call
}

// GetOrchestration is a helper method to define mock.On call
//   - ctx context.Context
//   - orchestrationID string
func (_e *MockProvisionManager_Expecter) GetOrchestration(ctx interface{}, orchestrationID interface{}) *MockProvisionManager_GetOrchestration_Call {
	return &MockProvisionManager_GetOrchestration_Call{Call: _e.mock.On("GetOrchestration", ctx, orchestrationID)}
}

func (_c *MockProvisionManager_GetOrchestration_Call) Run(run func(ctx context.Context, orchestrationID string)) *MockProvisionManager_GetOrchestration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProvisionManager_GetOrchestration_Call) Return(_a0 *api.Orchestration, _a1 error) *MockProvisionManager_GetOrchestration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvisionManager_GetOrchestration_Call) RunAndReturn(run func(context.Context, string) (*api.Orchestration, error)) *MockProvisionManager_GetOrchestration_Call {
	_c.Call.Return(run)
	return _c
}

// QueryOrchestrations provides a mock function with given fields: ctx, predicate, options
func (_m *MockProvisionManager) QueryOrchestrations(ctx context.Context, predicate query.Predicate, options store.PaginationOptions) iter.Seq2[*api.OrchestrationEntry, error] {
	ret := _m.Called(ctx, predicate, options)

	if len(ret) == 0 {
		panic("no return value specified for QueryOrchestrations")
	}

	var r0 iter.Seq2[*api.OrchestrationEntry, error]
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate, store.PaginationOptions) iter.Seq2[*api.OrchestrationEntry, error]); ok {
		r0 = rf(ctx, predicate, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[*api.OrchestrationEntry, error])
		}
	}

	return r0
}

// MockProvisionManager_QueryOrchestrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryOrchestrations'
type MockProvisionManager_QueryOrchestrations_Call struct {
	*mock.Call
}

// QueryOrchestrations is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
//   - options store.PaginationOptions
func (_e *MockProvisionManager_Expecter) QueryOrchestrations(ctx interface{}, predicate interface{}, options interface{}) *MockProvisionManager_QueryOrchestrations_Call {
	return &MockProvisionManager_QueryOrchestrations_Call{Call: _e.mock.On("QueryOrchestrations", ctx, predicate, options)}
}

func (_c *MockProvisionManager_QueryOrchestrations_Call) Run(run func(ctx context.Context, predicate query.Predicate, options store.PaginationOptions)) *MockProvisionManager_QueryOrchestrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate), args[2].(store.PaginationOptions))
	})
	return _c
}

func (_c *MockProvisionManager_QueryOrchestrations_Call) Return(_a0 iter.Seq2[*api.OrchestrationEntry, error]) *MockProvisionManager_QueryOrchestrations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvisionManager_QueryOrchestrations_Call) RunAndReturn(run func(context.Context, query.Predicate, store.PaginationOptions) iter.Seq2[*api.OrchestrationEntry, error]) *MockProvisionManager_QueryOrchestrations_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, manifest
func (_m *MockProvisionManager) Start(ctx context.Context, manifest *model.OrchestrationManifest) (*api.Orchestration, error) {
	ret := _m.Called(ctx, manifest)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *api.Orchestration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrchestrationManifest) (*api.Orchestration, error)); ok {
		return rf(ctx, manifest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrchestrationManifest) *api.Orchestration); ok {
		r0 = rf(ctx, manifest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Orchestration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.OrchestrationManifest) error); ok {
		r1 = rf(ctx, manifest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvisionManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProvisionManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - manifest *model.OrchestrationManifest
func (_e *MockProvisionManager_Expecter) Start(ctx interface{}, manifest interface{}) *MockProvisionManager_Start_Call {
	return &MockProvisionManager_Start_Call{Call: _e.mock.On("Start", ctx, manifest)}
}

func (_c *MockProvisionManager_Start_Call) Run(run func(ctx context.Context, manifest *model.OrchestrationManifest)) *MockProvisionManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OrchestrationManifest))
	})
	return _c
}

func (_c *MockProvisionManager_Start_Call) Return(_a0 *api.Orchestration, _a1 error) *MockProvisionManager_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvisionManager_Start_Call) RunAndReturn(run func(context.Context, *model.OrchestrationManifest) (*api.Orchestration, error)) *MockProvisionManager_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvisionManager creates a new instance of MockProvisionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvisionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvisionManager {
	mock := &MockProvisionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
