issue-845-fix: true
resolve-type-alias: false
disable-version-string: true
with-expecter: true
packages:
  github.com/eclipse-cfm/cfm/common/natsclient:
    interfaces:
      MsgClient:
        config:
          filename: msg_client_mock.go
          outpkg: mocks
          dir: ./mocks
  github.com/eclipse-cfm/cfm/common/store:
    interfaces:
      EntityStore:
        config:
          filename: store.go
          outpkg: mocks
          dir: ./mocks

  github.com/eclipse-cfm/cfm/common/token:
    interfaces:
      TokenProvider:
        config:
          filename: token_provider.go
          outpkg: mocks
          dir: ./mocks