// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/eclipse-cfm/cfm/pmanager/api"

	mock "github.com/stretchr/testify/mock"
)

// MockOrchestrator is an autogenerated mock type for the Orchestrator type
type MockOrchestrator struct {
	mock.Mock
}

type MockOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrchestrator) EXPECT() *MockOrchestrator_Expecter {
	return &MockOrchestrator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, orchestration
func (_m *MockOrchestrator) Execute(ctx context.Context, orchestration *api.Orchestration) error {
	ret := _m.Called(ctx, orchestration)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.Orchestration) error); ok {
		r0 = rf(ctx, orchestration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrchestrator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOrchestrator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - orchestration *api.Orchestration
func (_e *MockOrchestrator_Expecter) Execute(ctx interface{}, orchestration interface{}) *MockOrchestrator_Execute_Call {
	return &MockOrchestrator_Execute_Call{Call: _e.mock.On("Execute", ctx, orchestration)}
}

func (_c *MockOrchestrator_Execute_Call) Run(run func(ctx context.Context, orchestration *api.Orchestration)) *MockOrchestrator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*api.Orchestration))
	})
	return _c
}

func (_c *MockOrchestrator_Execute_Call) Return(_a0 error) *MockOrchestrator_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrchestrator_Execute_Call) RunAndReturn(run func(context.Context, *api.Orchestration) error) *MockOrchestrator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrchestration provides a mock function with given fields: ctx, id
func (_m *MockOrchestrator) GetOrchestration(ctx context.Context, id string) (*api.Orchestration, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrchestration")
	}

	var r0 *api.Orchestration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.Orchestration, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.Orchestration); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Orchestration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_GetOrchestration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrchestration'
type MockOrchestrator_GetOrchestration_Call struct {
	*mock.Call
}

// GetOrchestration is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrchestrator_Expecter) GetOrchestration(ctx interface{}, id interface{}) *MockOrchestrator_GetOrchestration_Call {
	return &MockOrchestrator_GetOrchestration_Call{Call: _e.mock.On("GetOrchestration", ctx, id)}
}

func (_c *MockOrchestrator_GetOrchestration_Call) Run(run func(ctx context.Context, id string)) *MockOrchestrator_GetOrchestration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrchestrator_GetOrchestration_Call) Return(_a0 *api.Orchestration, _a1 error) *MockOrchestrator_GetOrchestration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_GetOrchestration_Call) RunAndReturn(run func(context.Context, string) (*api.Orchestration, error)) *MockOrchestrator_GetOrchestration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrchestrator creates a new instance of MockOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrchestrator {
	mock := &MockOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
