// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	iter "iter"

	mock "github.com/stretchr/testify/mock"

	query "github.com/eclipse-cfm/cfm/common/query"

	store "github.com/eclipse-cfm/cfm/common/store"
)

// MockEntityStore is an autogenerated mock type for the EntityStore type
type MockEntityStore[T store.EntityType] struct {
	mock.Mock
}

type MockEntityStore_Expecter[T store.EntityType] struct {
	mock *mock.Mock
}

func (_m *MockEntityStore[T]) EXPECT() *MockEntityStore_Expecter[T] {
	return &MockEntityStore_Expecter[T]{mock: &_m.Mock}
}

// CountByPredicate provides a mock function with given fields: ctx, predicate
func (_m *MockEntityStore[T]) CountByPredicate(ctx context.Context, predicate query.Predicate) (int64, error) {
	ret := _m.Called(ctx, predicate)

	if len(ret) == 0 {
		panic("no return value specified for CountByPredicate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) (int64, error)); ok {
		return rf(ctx, predicate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) int64); ok {
		r0 = rf(ctx, predicate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Predicate) error); ok {
		r1 = rf(ctx, predicate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityStore_CountByPredicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByPredicate'
type MockEntityStore_CountByPredicate_Call[T store.EntityType] struct {
	*mock.Call
}

// CountByPredicate is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
func (_e *MockEntityStore_Expecter[T]) CountByPredicate(ctx interface{}, predicate interface{}) *MockEntityStore_CountByPredicate_Call[T] {
	return &MockEntityStore_CountByPredicate_Call[T]{Call: _e.mock.On("CountByPredicate", ctx, predicate)}
}

func (_c *MockEntityStore_CountByPredicate_Call[T]) Run(run func(ctx context.Context, predicate query.Predicate)) *MockEntityStore_CountByPredicate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate))
	})
	return _c
}

func (_c *MockEntityStore_CountByPredicate_Call[T]) Return(_a0 int64, _a1 error) *MockEntityStore_CountByPredicate_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityStore_CountByPredicate_Call[T]) RunAndReturn(run func(context.Context, query.Predicate) (int64, error)) *MockEntityStore_CountByPredicate_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, entity
func (_m *MockEntityStore[T]) Create(ctx context.Context, entity T) (T, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEntityStore_Create_Call[T store.EntityType] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity T
func (_e *MockEntityStore_Expecter[T]) Create(ctx interface{}, entity interface{}) *MockEntityStore_Create_Call[T] {
	return &MockEntityStore_Create_Call[T]{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockEntityStore_Create_Call[T]) Run(run func(ctx context.Context, entity T)) *MockEntityStore_Create_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockEntityStore_Create_Call[T]) Return(_a0 T, _a1 error) *MockEntityStore_Create_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityStore_Create_Call[T]) RunAndReturn(run func(context.Context, T) (T, error)) *MockEntityStore_Create_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEntityStore[T]) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEntityStore_Delete_Call[T store.EntityType] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEntityStore_Expecter[T]) Delete(ctx interface{}, id interface{}) *MockEntityStore_Delete_Call[T] {
	return &MockEntityStore_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEntityStore_Delete_Call[T]) Run(run func(ctx context.Context, id string)) *MockEntityStore_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEntityStore_Delete_Call[T]) Return(_a0 error) *MockEntityStore_Delete_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_Delete_Call[T]) RunAndReturn(run func(context.Context, string) error) *MockEntityStore_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteByPredicate provides a mock function with given fields: ctx, predicate
func (_m *MockEntityStore[T]) DeleteByPredicate(ctx context.Context, predicate query.Predicate) error {
	ret := _m.Called(ctx, predicate)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPredicate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) error); ok {
		r0 = rf(ctx, predicate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityStore_DeleteByPredicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPredicate'
type MockEntityStore_DeleteByPredicate_Call[T store.EntityType] struct {
	*mock.Call
}

// DeleteByPredicate is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
func (_e *MockEntityStore_Expecter[T]) DeleteByPredicate(ctx interface{}, predicate interface{}) *MockEntityStore_DeleteByPredicate_Call[T] {
	return &MockEntityStore_DeleteByPredicate_Call[T]{Call: _e.mock.On("DeleteByPredicate", ctx, predicate)}
}

func (_c *MockEntityStore_DeleteByPredicate_Call[T]) Run(run func(ctx context.Context, predicate query.Predicate)) *MockEntityStore_DeleteByPredicate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate))
	})
	return _c
}

func (_c *MockEntityStore_DeleteByPredicate_Call[T]) Return(_a0 error) *MockEntityStore_DeleteByPredicate_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_DeleteByPredicate_Call[T]) RunAndReturn(run func(context.Context, query.Predicate) error) *MockEntityStore_DeleteByPredicate_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, id
func (_m *MockEntityStore[T]) Exists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityStore_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockEntityStore_Exists_Call[T store.EntityType] struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEntityStore_Expecter[T]) Exists(ctx interface{}, id interface{}) *MockEntityStore_Exists_Call[T] {
	return &MockEntityStore_Exists_Call[T]{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockEntityStore_Exists_Call[T]) Run(run func(ctx context.Context, id string)) *MockEntityStore_Exists_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEntityStore_Exists_Call[T]) Return(_a0 bool, _a1 error) *MockEntityStore_Exists_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityStore_Exists_Call[T]) RunAndReturn(run func(context.Context, string) (bool, error)) *MockEntityStore_Exists_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockEntityStore[T]) FindByID(ctx context.Context, id string) (T, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (T, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) T); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEntityStore_FindByID_Call[T store.EntityType] struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEntityStore_Expecter[T]) FindByID(ctx interface{}, id interface{}) *MockEntityStore_FindByID_Call[T] {
	return &MockEntityStore_FindByID_Call[T]{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockEntityStore_FindByID_Call[T]) Run(run func(ctx context.Context, id string)) *MockEntityStore_FindByID_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEntityStore_FindByID_Call[T]) Return(_a0 T, _a1 error) *MockEntityStore_FindByID_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityStore_FindByID_Call[T]) RunAndReturn(run func(context.Context, string) (T, error)) *MockEntityStore_FindByID_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindByPredicate provides a mock function with given fields: ctx, predicate
func (_m *MockEntityStore[T]) FindByPredicate(ctx context.Context, predicate query.Predicate) iter.Seq2[T, error] {
	ret := _m.Called(ctx, predicate)

	if len(ret) == 0 {
		panic("no return value specified for FindByPredicate")
	}

	var r0 iter.Seq2[T, error]
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) iter.Seq2[T, error]); ok {
		r0 = rf(ctx, predicate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[T, error])
		}
	}

	return r0
}

// MockEntityStore_FindByPredicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPredicate'
type MockEntityStore_FindByPredicate_Call[T store.EntityType] struct {
	*mock.Call
}

// FindByPredicate is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
func (_e *MockEntityStore_Expecter[T]) FindByPredicate(ctx interface{}, predicate interface{}) *MockEntityStore_FindByPredicate_Call[T] {
	return &MockEntityStore_FindByPredicate_Call[T]{Call: _e.mock.On("FindByPredicate", ctx, predicate)}
}

func (_c *MockEntityStore_FindByPredicate_Call[T]) Run(run func(ctx context.Context, predicate query.Predicate)) *MockEntityStore_FindByPredicate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate))
	})
	return _c
}

func (_c *MockEntityStore_FindByPredicate_Call[T]) Return(_a0 iter.Seq2[T, error]) *MockEntityStore_FindByPredicate_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_FindByPredicate_Call[T]) RunAndReturn(run func(context.Context, query.Predicate) iter.Seq2[T, error]) *MockEntityStore_FindByPredicate_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindByPredicatePaginated provides a mock function with given fields: ctx, predicate, opts
func (_m *MockEntityStore[T]) FindByPredicatePaginated(ctx context.Context, predicate query.Predicate, opts store.PaginationOptions) iter.Seq2[T, error] {
	ret := _m.Called(ctx, predicate, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindByPredicatePaginated")
	}

	var r0 iter.Seq2[T, error]
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate, store.PaginationOptions) iter.Seq2[T, error]); ok {
		r0 = rf(ctx, predicate, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[T, error])
		}
	}

	return r0
}

// MockEntityStore_FindByPredicatePaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPredicatePaginated'
type MockEntityStore_FindByPredicatePaginated_Call[T store.EntityType] struct {
	*mock.Call
}

// FindByPredicatePaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
//   - opts store.PaginationOptions
func (_e *MockEntityStore_Expecter[T]) FindByPredicatePaginated(ctx interface{}, predicate interface{}, opts interface{}) *MockEntityStore_FindByPredicatePaginated_Call[T] {
	return &MockEntityStore_FindByPredicatePaginated_Call[T]{Call: _e.mock.On("FindByPredicatePaginated", ctx, predicate, opts)}
}

func (_c *MockEntityStore_FindByPredicatePaginated_Call[T]) Run(run func(ctx context.Context, predicate query.Predicate, opts store.PaginationOptions)) *MockEntityStore_FindByPredicatePaginated_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate), args[2].(store.PaginationOptions))
	})
	return _c
}

func (_c *MockEntityStore_FindByPredicatePaginated_Call[T]) Return(_a0 iter.Seq2[T, error]) *MockEntityStore_FindByPredicatePaginated_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_FindByPredicatePaginated_Call[T]) RunAndReturn(run func(context.Context, query.Predicate, store.PaginationOptions) iter.Seq2[T, error]) *MockEntityStore_FindByPredicatePaginated_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindFirstByPredicate provides a mock function with given fields: ctx, predicate
func (_m *MockEntityStore[T]) FindFirstByPredicate(ctx context.Context, predicate query.Predicate) (T, error) {
	ret := _m.Called(ctx, predicate)

	if len(ret) == 0 {
		panic("no return value specified for FindFirstByPredicate")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) (T, error)); ok {
		return rf(ctx, predicate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Predicate) T); ok {
		r0 = rf(ctx, predicate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Predicate) error); ok {
		r1 = rf(ctx, predicate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityStore_FindFirstByPredicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirstByPredicate'
type MockEntityStore_FindFirstByPredicate_Call[T store.EntityType] struct {
	*mock.Call
}

// FindFirstByPredicate is a helper method to define mock.On call
//   - ctx context.Context
//   - predicate query.Predicate
func (_e *MockEntityStore_Expecter[T]) FindFirstByPredicate(ctx interface{}, predicate interface{}) *MockEntityStore_FindFirstByPredicate_Call[T] {
	return &MockEntityStore_FindFirstByPredicate_Call[T]{Call: _e.mock.On("FindFirstByPredicate", ctx, predicate)}
}

func (_c *MockEntityStore_FindFirstByPredicate_Call[T]) Run(run func(ctx context.Context, predicate query.Predicate)) *MockEntityStore_FindFirstByPredicate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Predicate))
	})
	return _c
}

func (_c *MockEntityStore_FindFirstByPredicate_Call[T]) Return(_a0 T, _a1 error) *MockEntityStore_FindFirstByPredicate_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityStore_FindFirstByPredicate_Call[T]) RunAndReturn(run func(context.Context, query.Predicate) (T, error)) *MockEntityStore_FindFirstByPredicate_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockEntityStore[T]) GetAll(ctx context.Context) iter.Seq2[T, error] {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 iter.Seq2[T, error]
	if rf, ok := ret.Get(0).(func(context.Context) iter.Seq2[T, error]); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[T, error])
		}
	}

	return r0
}

// MockEntityStore_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockEntityStore_GetAll_Call[T store.EntityType] struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEntityStore_Expecter[T]) GetAll(ctx interface{}) *MockEntityStore_GetAll_Call[T] {
	return &MockEntityStore_GetAll_Call[T]{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockEntityStore_GetAll_Call[T]) Run(run func(ctx context.Context)) *MockEntityStore_GetAll_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEntityStore_GetAll_Call[T]) Return(_a0 iter.Seq2[T, error]) *MockEntityStore_GetAll_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_GetAll_Call[T]) RunAndReturn(run func(context.Context) iter.Seq2[T, error]) *MockEntityStore_GetAll_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetAllCount provides a mock function with given fields: ctx
func (_m *MockEntityStore[T]) GetAllCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntityStore_GetAllCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCount'
type MockEntityStore_GetAllCount_Call[T store.EntityType] struct {
	*mock.Call
}

// GetAllCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEntityStore_Expecter[T]) GetAllCount(ctx interface{}) *MockEntityStore_GetAllCount_Call[T] {
	return &MockEntityStore_GetAllCount_Call[T]{Call: _e.mock.On("GetAllCount", ctx)}
}

func (_c *MockEntityStore_GetAllCount_Call[T]) Run(run func(ctx context.Context)) *MockEntityStore_GetAllCount_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEntityStore_GetAllCount_Call[T]) Return(_a0 int64, _a1 error) *MockEntityStore_GetAllCount_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntityStore_GetAllCount_Call[T]) RunAndReturn(run func(context.Context) (int64, error)) *MockEntityStore_GetAllCount_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetAllPaginated provides a mock function with given fields: ctx, opts
func (_m *MockEntityStore[T]) GetAllPaginated(ctx context.Context, opts store.PaginationOptions) iter.Seq2[T, error] {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPaginated")
	}

	var r0 iter.Seq2[T, error]
	if rf, ok := ret.Get(0).(func(context.Context, store.PaginationOptions) iter.Seq2[T, error]); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[T, error])
		}
	}

	return r0
}

// MockEntityStore_GetAllPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPaginated'
type MockEntityStore_GetAllPaginated_Call[T store.EntityType] struct {
	*mock.Call
}

// GetAllPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - opts store.PaginationOptions
func (_e *MockEntityStore_Expecter[T]) GetAllPaginated(ctx interface{}, opts interface{}) *MockEntityStore_GetAllPaginated_Call[T] {
	return &MockEntityStore_GetAllPaginated_Call[T]{Call: _e.mock.On("GetAllPaginated", ctx, opts)}
}

func (_c *MockEntityStore_GetAllPaginated_Call[T]) Run(run func(ctx context.Context, opts store.PaginationOptions)) *MockEntityStore_GetAllPaginated_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.PaginationOptions))
	})
	return _c
}

func (_c *MockEntityStore_GetAllPaginated_Call[T]) Return(_a0 iter.Seq2[T, error]) *MockEntityStore_GetAllPaginated_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_GetAllPaginated_Call[T]) RunAndReturn(run func(context.Context, store.PaginationOptions) iter.Seq2[T, error]) *MockEntityStore_GetAllPaginated_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, entity
func (_m *MockEntityStore[T]) Update(ctx context.Context, entity T) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEntityStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEntityStore_Update_Call[T store.EntityType] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entity T
func (_e *MockEntityStore_Expecter[T]) Update(ctx interface{}, entity interface{}) *MockEntityStore_Update_Call[T] {
	return &MockEntityStore_Update_Call[T]{Call: _e.mock.On("Update", ctx, entity)}
}

func (_c *MockEntityStore_Update_Call[T]) Run(run func(ctx context.Context, entity T)) *MockEntityStore_Update_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockEntityStore_Update_Call[T]) Return(_a0 error) *MockEntityStore_Update_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEntityStore_Update_Call[T]) RunAndReturn(run func(context.Context, T) error) *MockEntityStore_Update_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockEntityStore creates a new instance of MockEntityStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntityStore[T store.EntityType](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntityStore[T] {
	mock := &MockEntityStore[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
